---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-01-20 - 22:18:41 +0000
  labels:
    app.kubernetes.io/name: workshop
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: workshop
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/name: workshop
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-01-20 - 22:18:41 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: workshop
  name: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: workshop
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-01-20 - 22:18:41 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: workshop
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ahmed/workshop:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: workshop
        ports:
        - containerPort: 8083
          name: http
          protocol: TCP
